reporter_app/users/__init__.py
from flask import Blueprint

bp = Blueprint('users', __name__)

from reporter_app.users import routes
from reporter_app.users import forms

reporter_app/users/routes.py
from flask import flash, request
from flask import render_template, url_for, redirect
from reporter_app.users import bp
from reporter_app.models import User, Role
from reporter_app import db
from flask_security import auth_required, current_user, roles_required


@bp.route('/user/<id>')
@auth_required("token", "session")
def user(id):
	user = User.query.filter_by(id=id).first_or_404()
	# If the user accessing the page has permission render user
	if user.id == current_user.id or (current_user.has_role('admin') and current_user.has_role('verified')):  # Only user owner and admin allowed
		# Get all roles according to the user
		roles = Role.query.all()
		hasRoles = []
		otherRoles = []
		for role in roles:
			# We manage verified role seperatly
			if role.name == 'verified':
				continue
			if user.has_role(role.name):
				hasRoles.append(role)
			else:
				otherRoles.append(role)
		return render_template('users/user.html', user=user, has_roles=hasRoles, other_roles=otherRoles)
	# If the user does not have permission then redirect to dashboard
	flash('You do not have permission to do that', 'danger')
	return redirect(url_for('dashboard.dashboard'))


@bp.route('/users/')
@auth_required("token", "session")
@roles_required('verified', 'admin')
def users():
	# If the user accessing the page has permission render users
	if current_user.has_role('admin'):  # Only user owner and admin allowed
		users = User.query.all()
		return render_template('users/users.html', users=users)
	# If the user does not have permission then redirect to dashboard
	flash('You do not have permission to do that', 'danger')
	return redirect(url_for('dashboard.dashboard'))


@bp.route('/user/<id>/toggle_role/<role_name>')
@auth_required("token", "session")
def toggle_user_role(id, role_name):
	user = User.query.filter_by(id=id).first_or_404()
	# If the user accessing the route has permission render user
	# A user has to be an admin, verified and a user cannot change their own permissions
	if (current_user.id != int(id)) and current_user.has_role('admin') and current_user.has_role('verified'):
		role = Role.query.filter_by(name=role_name).first()
		if user.has_role(role_name):
			user.roles.remove(role)
			db.session.commit()
		else:
			user.roles.append(role)
			db.session.commit()
		return redirect(url_for('users.user', id=user.id))
	# If the user does not have permission then reload user template
	flash('You do not have permission to do that', 'danger')
	#return redirect(url_for('users.user', id=user.id), code=403)
	return render_template('errors/403.html'), 403

reporter_app/templates/users/user.html
{% extends "template_parts/base.html" %}

{% block content %}
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
  <div class="bg-white p-3 mt-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3">
      <h1 class="h2">Profile</h1>
    </div>
		<hr/>

    <h2>About</h2>
    <div class="row">
      <div class="col col-12 col-md-6"><p><span class="h6">First name:</span> {{ user.first_name }}</p></div>
      <div class="col col-12 col-md-6"><p><span class="h6">Surname:</span> {{ user.surname }}</p></div>
    </div>
    <div class="row">
      <div class="col col-12 col-md-6"><p><span class="h6">ID:</span> {{ user.id }}</p></div>
      <div class="col col-12 col-md-6"><p><span class="h6">Email:</span> {{ user.email }}</p></div>
    </div>
    <div class="row">
      <div class="col col-12 col-md-6"><p><span class="h6">Username:</span> {{ user.username if user.username != none }}</p></div>
      <div class="col col-12 col-md-6">
				<p>
					<span class="h6">Roles:</span>
					{% for role in user.roles %}
						<span class="badge rounded-pill bg-secondary">{{role.name}}</span>
					{% endfor %}
				</p>
			</div>
    </div>

    <h2>Info</h2>
		<div class="row">
			<div class="col col-12 col-md-6"><p><span class="h6">Last login time:</span> {{ user.last_login_at.strftime("%m/%d/%Y, %H:%M:%S") if user.last_login_at else user.last_login_at }}</p></div>
			<div class="col col-12 col-md-6"><p><span class="h6">Current login time:</span> {{ user.current_login_at.strftime("%m/%d/%Y, %H:%M:%S") if user.current_login_at else user.current_login_at }}</p></div>
		</div>
    <div class="row">
      <div class="col col-12 col-md-6"><p><span class="h6">Last login IP:</span> {{ user.last_login_ip }}</p></div>
      <div class="col col-12 col-md-6"><p><span class="h6">Current login IP:</span> {{ user.current_login_ip }}</p></div>
    </div>
    <div class="row">
      <div class="col col-12 col-md-6"><p><span class="h6">Login count:</span> {{ user.login_count }}</p></div>
			<div class="col col-12 col-md-6"><p><span class="h6">Confirmed at:</span> {{ user.confirmed_at.strftime("%m/%d/%Y, %H:%M:%S") if user.confirmed_at else user.confirmed_at }}</p></div>
    </div>
    <div class="row">
      <div class="col col-12 col-md-6"><p><span class="h6">Created at:</span> {{ user.create_datetime.strftime("%m/%d/%Y, %H:%M:%S") if user.create_datetime else user.create_datetime }}</p></div>
      <div class="col col-12 col-md-6"><p><span class="h6">Last updated at:</span> {{ user.update_datetime.strftime("%m/%d/%Y, %H:%M:%S") if user.update_datetime else user.update_datetime }}</p></div>
    </div>
			<hr/>
			<h2>Actions</h2>
			<div class="">
			{% if user.id == current_user.id %}
				<a class="btn btn-outline-secondary d-md-inline d-sm-block" href="{{ url_for_security('change_password') }}">Update password</a>
			{% endif %}
			{% if current_user.has_role('admin') and current_user.has_role('verified') and user.id != current_user.id %}
				<a class="btn btn-outline-{{ 'danger' if user.has_role('verified') else 'success'}} d-md-inline d-sm-block mb-2" href="{{ url_for('users.toggle_user_role', id=user.id, role_name='verified') }}">{{ 'Unverify' if user.has_role('verified') else 'Verify'}}</a>

				<div class="dropdown d-md-inline d-sm-block mb-2">
					<button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuAddRole" data-bs-toggle="dropdown" aria-expanded="false">
						Add Role
					</button>
					<ul class="dropdown-menu" aria-labelledby="dropdownMenuAddRole">
						{% for role in other_roles %}
							<li><a class="dropdown-item" href="{{ url_for('users.toggle_user_role', id=user.id, role_name=role.name) }}">{{role.name}}</a></li>
						{% endfor %}
					</ul>
				</div>

				<div class="dropdown d-md-inline d-sm-block mb-2">
					<button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuRemoveRole" data-bs-toggle="dropdown" aria-expanded="false">
						Remove Role
					</button>
					<ul class="dropdown-menu" aria-labelledby="dropdownMenuRemoveRole">
						{% for role in has_roles %}
							<li><a class="dropdown-item" href="{{ url_for('users.toggle_user_role', id=user.id, role_name=role.name) }}">{{role.name}}</a></li>
						{% endfor %}
					</ul>
				</div>
			{% endif %}
			</div>
  </div>
</main>
{% endblock %}

reporter_app/templates/users/users.html
{% extends "template_parts/base.html" %}

{% block content %}
<main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
  <div class="bg-white p-3 mt-4">
    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3">
      <h1 class="h2">Users</h1>
    </div>
		<hr/>

		<table class="table table-striped">
			<thead>
		    <tr>
		      <th scope="col">ID</th>
		      <th scope="col">First name</th>
		      <th scope="col">Surname</th>
		      <th scope="col">Email</th>
					<th scope="col">Roles</th>
					<th scope="col">Actions</th>
		    </tr>
		  </thead>
			<tbody>
				{% for user in users %}
				<tr>
					<th scope="row">{{ user.id }}</th>
					<td>{{ user.first_name }}</td>
					<td>{{ user.surname }}</td>
					<td>{{ user.email }}</td>
					<td>
						{% for role in user.roles %}
							<span class="badge rounded-pill bg-secondary">{{role.name}}</span>
						{% endfor %}
					</td>
					<td><a type="button" class="btn btn-outline-primary btn-sm" href="{{ url_for('users.user', id=user.id) }}">View</a></td>
				</tr>
				{% endfor %}
			</tbody>
		</table>
  </div>
</main>
{% endblock %}